/// @description Aqui ficam as variáveis
// You can write your code in this editor
gun=0
gunmax=5
debug=0
initpulo =16
jumptime=0
jumptimemax=5
alturapulo=4.3
walljump_alturapulo=14
verticalspdmin=-40
verticalspdmax=40
verticalspdminnormal=-40
verticalspdmaxnormal=40
verticalspd=0
gravid=1.6
gravidnormal=1.6
horizontalspd=0
direcao=0
velocidade=0
velocidademaxima=6.5
aceleracao=0.8
desaceleracao=3
coyotetime=0
coyotetimemax=3.25
pulos=2
podepular=true
podemexer=0
x_scale=1
y_scale=1
skin=0
walltime=0
walltime_max = 60
estado = scr_nedekyn_livre
alarm3=20
velocidadegrama=5.5