/// @description Aqui ficam as variáveis
// You can write your code in this editor
initpulo =8
jumptime=0
jumptimemax=5
alturapulo=2
walljump_alturapulo=8
verticalspdmin=-13
verticalspdmax=13
verticalspdminnormal=-13
verticalspdmaxnormal=13
verticalspd=0
gravid=0.38
gravidnormal=0.38
horizontalspd=0
direcao=0
velocidade=0
velocidademaxima=4
aceleracao=0.4
desaceleracao=0.5
coyotetime=0
coyotetimemax=8
pulos=2
podepular=true
podemexer=0
x_scale=1
y_scale=1
skin=0
walltime=0
walltime_max = 120
estado = scr_nedekyn_livre
alarm3=45
velocidadegrama=3.0